const albumGoogleDrive = [
    { nome: "5.", link: "GoogleDrive/5.jpg",
        data: "Friday, March 26, 2021 at 18:49",
        localizacao: "Sintra, Portugal",
        gps: "(40.7128, -74.0060)",
        dispositivo: "Apple iPhone 13 mini",
        camera: "Main Camera -- 26 mm f1.6",
        metadados: "24 MP * 4284 x 5712 * 2.3 MB",
        avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
        pessoas: "Winona Ryder",
        notas: "",
        filtro: ["Sintra", "Winona Ryder"],
        emocao: "happiness",
        emocao: "happiness"},
    { nome: "6.", link: "GoogleDrive/6.jpg",
        data: "Saturday, March 27, 2021 at 14:09",
        localizacao: "Sintra, Portugal",
        gps: "(40.7128, -74.0060)",
        dispositivo: "Apple iPhone 13 mini",
        camera: "Main Camera -- 26 mm f1.6",
        metadados: "24 MP * 4284 x 5712 * 2.3 MB",
        avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
        pessoas: "Winona Ryder",
        notas: "",
        filtro: ["Sintra", "Winona Ryder"],
        emocao: "happiness",
        emocao: "happiness"},
    { nome: "7.", link: "GoogleDrive/7.jpg",
        data: "Tuesday, March 30, 2021 at 12:39",
        localizacao: "Sintra, Portugal",
        gps: "(40.7128, -74.0060)",
        dispositivo: "Apple iPhone 13 mini",
        camera: "Main Camera -- 26 mm f1.6",
        metadados: "24 MP * 4284 x 5712 * 2.3 MB",
        avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
        pessoas: "Winona Ryder",
        notas: "",
        filtro: ["Sintra", "Winona Ryder"],
        emocao: "happiness",
        emocao: "happiness"},
    { nome: "8.", link: "GoogleDrive/8.jpg",
        data: "Tuesday, April 6, 2021 at 10:19",
        localizacao: "Peneda-Gerês National Park, Portugal",
        gps: "(51.5074, -0.1278)",
        dispositivo: "Apple iPhone 13 mini",
        camera: "Main Camera -- 26 mm f1.6",
        metadados: "24 MP * 4284 x 5712 * 2.3 MB",
        avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
        notas: "",
        filtro: ["Peneda-Gerês National Park", "Winona Ryder"],
        emocao: "happiness",
        emocao: "happiness"},
    { nome: "9.", link: "GoogleDrive/9.jpg",
        data: "Thursday, April 8, 2021 at 11:59",
        localizacao: "Peneda-Gerês National Park, Portugal",
        gps: "(51.5074, -0.1278)",
        dispositivo: "Apple iPhone 13 mini",
        camera: "Main Camera -- 26 mm f1.6",
        metadados: "24 MP * 4284 x 5712 * 2.3 MB",
        avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
        pessoas: "Winona Ryder",
        notas: "",
        filtro: ["Peneda-Gerês National Park", "Winona Ryder"],
        emocao: "happiness",
        emocao: "happiness"},
    { nome: "10.", link: "GoogleDrive/10.jpg",
        data: "Sunday, April 14, 2021 at 13:05",
        localizacao: "Peneda-Gerês National Park, Portugal",
        gps: "(51.5074, -0.1278)",
        dispositivo: "Apple iPhone 13 mini",
        camera: "Main Camera -- 26 mm f1.6",
        metadados: "24 MP * 4284 x 5712 * 2.3 MB",
        avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
        pessoas: "Winona Ryder",
        notas: "",
        filtro: ["Peneda-Gerês National Park", "Winona Ryder"],
        emocao: "happiness",
        emocao: "happiness"},
    { nome: "11.", link: "GoogleDrive/11.jpg",
        data: "Saturday, November 3, 2023 at 15:15",
        localizacao: "Amazon, Brazil",
        gps: "(35.6895, 139.6917)",
        dispositivo: "Apple iPhone 13 mini",
        camera: "Main Camera -- 26 mm f1.6",
        metadados: "24 MP * 4284 x 5712 * 2.3 MB",
        avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
        pessoas: "Winona Ryder",
        notas: "",
        filtro: ["Amazon", "Winona Ryder", "Brazil"],
        emocao: "happiness"},
    { nome: "12.", link: "GoogleDrive/12.jpg",
        data: "Sunday, November 24, 2023 at 17:55",
        localizacao: "Amazon, Brazil",
        gps: "(35.6895, 139.6917)",
        dispositivo: "Apple iPhone 13 mini",
        camera: "Main Camera -- 26 mm f1.6",
        metadados: "24 MP * 4284 x 5712 * 2.3 MB",
        avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
        pessoas: "Winona Ryder",
        notas: "",
        filtro: ["Amazon", "Winona Ryder", "Brazil"],
        emocao: "happiness"},
    { nome: "13.", link: "GoogleDrive/13.jpg",
        data: "Monday, November 25, 2023 at 18:40",
        localizacao: "Amazon, Brazil",
        gps: "(35.6895, 139.6917)",
        dispositivo: "Apple iPhone 13 mini",
        camera: "Main Camera -- 26 mm f1.6",
        metadados: "24 MP * 4284 x 5712 * 2.3 MB",
        avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
        pessoas: "Winona Ryder",
        notas: "",
        filtro: ["Amazon", "Winona Ryder", "Brazil"],
        emocao: "happiness"},
    { nome: "14.", link: "GoogleDrive/14.jpg",
        data: "Friday, December 1, 2023 at 13:00",
        localizacao: "Amazon, Brazil",
        gps: "(35.6895, 139.6917)",
        dispositivo: "Apple iPhone 15",
        camera: "Main Camera -- 26 mm f1.6",
        metadados: "24 MP * 4284 x 5712 * 2.3 MB",
        avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
        pessoas: "Winona Ryder",
        notas: "",
        filtro: ["Amazon", "Winona Ryder", "Brazil", "iPhone 15"],
        emocao: "happiness"},
    { nome: "15.", link: "GoogleDrive/15.jpg",
        data: "Wednesday, May 8, 2024 at 16:55",
        localizacao: "Serengeti, Tanzania",
        gps: "(-23.5505, -46.6333)",
        dispositivo: "Apple iPhone 15",
        camera: "Main Camera -- 26 mm f1.6",
        metadados: "24 MP * 4284 x 5712 * 2.3 MB",
        avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
        pessoas: "Winona Ryder",
        notas: "",
        filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
        emocao: "happiness"},
    { nome: "16.", link: "GoogleDrive/2.jpg",
        data: "Wednesday, October 2, 2024 at 13:13",
        localizacao: "Serengeti, Tanzania",
        gps: "(-23.5505, -46.6333)",
        dispositivo: "Apple iPhone 15",
        camera: "Main Camera -- 26 mm f1.6",
        metadados: "24 MP * 4284 x 5712 * 2.3 MB",
        avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
        pessoas: "Winona Ryder",
        notas: "",
        filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
        emocao: "happiness"},
        { nome: "17.", link: "GoogleDrive/17.jpg",
            data: "Tuesday, October 8, 2024 at 09:00",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "18.", link: "GoogleDrive/18.jpg",
            data: "Wednesday, October 9, 2024 at 10:15",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "19.", link: "GoogleDrive/19.jpg",
            data: "Thursday, October 10, 2024 at 11:30",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "20.", link: "GoogleDrive/20.jpg",
            data: "Friday, October 11, 2024 at 12:45",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "21.", link: "GoogleDrive/21.jpg",
            data: "Saturday, October 12, 2024 at 13:00",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "22.", link: "GoogleDrive/22.jpg",
            data: "Sunday, October 13, 2024 at 14:15",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "23.", link: "GoogleDrive/23.jpg",
            data: "Monday, October 14, 2024 at 08:00",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "24.", link: "GoogleDrive/24.jpg",
            data: "Tuesday, October 15, 2024 at 09:15",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "25.", link: "GoogleDrive/25.jpg",
            data: "Monday, October 14, 2024 at 09:30",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "26.", link: "GoogleDrive/26.jpg",
            data: "Tuesday, October 15, 2024 at 08:45",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "27.", link: "GoogleDrive/27.jpg",
            data: "Wednesday, October 16, 2024 at 10:30",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "28.", link: "GoogleDrive/28.jpg",
            data: "Thursday, October 17, 2024 at 14:00",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "29.", link: "GoogleDrive/29.jpg",
            data: "Friday, October 18, 2024 at 15:30",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "30.", link: "GoogleDrive/30.jpg",
            data: "Saturday, October 19, 2024 at 12:00",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "31.", link: "GoogleDrive/31.jpg",
            data: "Sunday, October 20, 2024 at 14:15",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          },
          { nome: "32.", link: "GoogleDrive/32.jpg",
            data: "Monday, October 21, 2024 at 10:00",
            localizacao: "Serengeti, Tanzania",
            gps: "(-23.5505, -46.6333)",
            dispositivo: "Apple iPhone 15",
            camera: "Main Camera -- 26 mm f1.6",
            metadados: "24 MP * 4284 x 5712 * 2.3 MB",
            avancados: "ISO125 / 26mm / 0ev / f1.6 / 1/100s",
            pessoas: "Winona Ryder",
            notas: "",
            filtro: ["Serengeti", "Winona Ryder", "Tanzania", "iPhone 15"],
            emocao: "happiness"
          }
      ]
        




// Tenta carregar "allPictures" do localStorage
let GoogleDrive = JSON.parse(localStorage.getItem("albuns_import")) || {};

if(GoogleDrive == null){
    GoogleDrive = []
}
if(GoogleDrive["GoogleDrive"] == undefined){
    // Se "GoogleDrive" não existir, inicializa-o com o conteúdo do "album"
    GoogleDrive["GoogleDrive"] = albumGoogleDrive;
    localStorage.setItem("albuns_import", JSON.stringify(GoogleDrive));

}
